### PR TITLE
chore: move design-tokens into merged-packages as part of migration process

### PR DESCRIPTION
**Pull request by georgewrmarshall**
Duplicate of https://github.com/MetaMask/metamask-design-system/pull/92 with updated `main` branch

## **Description**

This PR follows **[PR#6] 1. Migrate the source repo's git history into the merged-packages/ temporary directory in metamask design system** as part of the [package migration process guide](https://github.com/MetaMask/metamask-design-system/blob/main/docs/package-migration-process-guide.md#pr6-1-migrate-the-source-repos-git-history-into-the-merged-packages-temporary-directory-in-metamask-design-system). This step migrates the Git history of the `design-tokens` repository into the `metamask-design-system` monorepo, placing all contents under the `merged-packages/design-tokens` directory.

[Example PR](https://github.com/MetaMask/core/pull/1872) in core

## **Related issues**

Partly fixes: https://github.com/MetaMask/metamask-design-system/issues/88

## **Manual testing steps**

1. Check the contents under `merged-packages/design-tokens` in the `metamask-design-system` repository to ensure the file structure aligns with the original `design-tokens` repository.
2. Verify that the commit history within `merged-packages/design-tokens` accurately preserves previous `design-tokens` commits.
3. Confirm successful integration within the monorepo and that no errors are introduced.

## **Pre-merge author checklist**

- [x] Verified `git-filter-repo` installation and migration process.
- [x] Confirmed all `design-tokens` files are correctly moved to `merged-packages/design-tokens`.
- [x] Checked that the full commit history for `design-tokens` is retained.
- [x] Followed MetaMask Coding Standards.
- [x] Set PR status appropriately.

## **Pre-merge reviewer checklist**

- [ ] Confirmed that all `design-tokens` files appear in `merged-packages/design-tokens` with the correct structure.
- [ ] Verified the commit history for `design-tokens` is intact and accurately reflects the original repository.
- [ ] Ensured this PR meets all acceptance criteria.

### CODE REVIEW

**Comment by georgewrmarshall** [comment]
@SocketSecurity ignore-all
- Acceptable risk as lavamoat protects us from supply chain attacks and most of these dependencies will be consolidated in the next step

Screenshot 2024-11-12 at 12 48 42 PM

**Review by brianacnguyen — APPROVED** [review]

**Comment by mcmire** [comment]
Performed the same checks that @MajorLift did in https://github.com/MetaMask/metamask-design-system/pull/92#pullrequestreview-2429101312.

- Confirmed that all design-tokens files appear in merged-packages/design-tokens with the correct structure using these commands:

  ```
  git remote add -f design-tokens https://github.com/MetaMask/design-tokens
  git remote update
  git diff HEAD:merged-packages/design-tokens remotes/design-tokens/main
  ```

- Verified the commit history for design-tokens is intact and accurately reflects the original repository. I got the same output that @MajorLift posted earlier.

- Ensured this PR meets all acceptance criteria.

**Review by mcmire — APPROVED** [review]
LGTM.

**Comment by mcmire** [comment]
Once again just as a reminder make sure to press the dropdown next to the green button and select "Create a merge commit" :)

**Pull request merged**
