### PR TITLE
chore: move design-tokens into merged-packages as part of migration process

### PR DESCRIPTION
**Pull request by georgewrmarshall**
## **Description**

This PR follows **[PR#6] 1. Migrate the source repo's git history into the merged-packages/ temporary directory in metamask design system** as part of the [package migration process guide](https://github.com/MetaMask/metamask-design-system/blob/main/docs/package-migration-process-guide.md#pr6-1-migrate-the-source-repos-git-history-into-the-merged-packages-temporary-directory-in-metamask-design-system). This step migrates the Git history of the `design-tokens` repository into the `metamask-design-system` monorepo, placing all contents under the `merged-packages/design-tokens` directory.

[Example PR](https://github.com/MetaMask/core/pull/1872) in core

## **Related issues**

Partly fixes: https://github.com/MetaMask/metamask-design-system/issues/88

## **Manual testing steps**

1. Check the contents under `merged-packages/design-tokens` in the `metamask-design-system` repository to ensure the file structure aligns with the original `design-tokens` repository.
2. Verify that the commit history within `merged-packages/design-tokens` accurately preserves previous `design-tokens` commits.
3. Confirm successful integration within the monorepo and that no errors are introduced.

## **Pre-merge author checklist**

- [x] Verified `git-filter-repo` installation and migration process.
- [x] Confirmed all `design-tokens` files are correctly moved to `merged-packages/design-tokens`.
- [x] Checked that the full commit history for `design-tokens` is retained.
- [x] Followed MetaMask Coding Standards.
- [x] Set PR status appropriately.

## **Pre-merge reviewer checklist**

- [ ] Confirmed that all `design-tokens` files appear in `merged-packages/design-tokens` with the correct structure.
- [ ] Verified the commit history for `design-tokens` is intact and accurately reflects the original repository.
- [ ] Ensured this PR meets all acceptance criteria.

### CODE REVIEW

**Comment by georgewrmarshall** [comment]
@SocketSecurity ignore-all
- Acceptable risk as lavamoat protects us from supply chain attacks and most of these dependencies will be consolidated in the next step

Screenshot 2024-11-08 at 3 11 23 PM

**Review by MajorLift — APPROVED** [review]
- [x] Confirmed that all design-tokens files appear in `merged-packages/design-tokens` with the correct structure.

Verified that no diffs are found when comparing the migrated package with the main branch of the original repo using the following commands:

```sh
git remote add -f design-tokens https://github.com/MetaMask/design-tokens
git remote update
git diff HEAD:merged-packages/design-tokens remotes/design-tokens/main
```

- [x] Verified the commit history for design-tokens is intact and accurately reflects the original repository.

Commit history is linear, and its readability is not affected by the [excessive merge commits issue](https://github.com/MetaMask/core/pull/1804#issuecomment-1771445829).

Screenshot 2024-11-12 at 4 28 56 AM

There's one section prior to the version reset that has nested merge commits, but this doesn't hurt readability or maintainability, and deserves to be preserved as a part of the package's development history.

Screenshot 2024-11-12 at 4 29 09 AM

- [x] Ensured this PR meets all acceptance criteria.

Correctly implements the requirements of [PR#6](https://github.com/MetaMask/metamask-design-system/blob/main/docs/package-migration-process-guide.md#pr6-1-migrate-the-source-repos-git-history-into-the-merged-packages-temporary-directory-in-metamask-design-system).

**Review by brianacnguyen — APPROVED** [review]

**Comment by mcmire** [comment]
**Remember to NOT squash + merge this branch. Please let me know when you want to merge this PR and I can enable "merge commits" on this repo.**

**Comment by georgewrmarshall** [comment]
Moving to new PR that is up to date with `main` https://github.com/MetaMask/metamask-design-system/pull/100

**Pull request closed without merging**
